version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Create .env
          command: |
            cat << EOF >> .env
            UID=$(id -u)
            GID=$(id -g)
            EOF
      - run:
          name: Build Docker Image
          command: docker-compose build
      - run:
          name: Docker-compose Up
          command: docker-compose up -d
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait DB container process up
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Run tests
          command: docker-compose exec app pipenv run scripts/run_tests
