version: 2
jobs:
  build:
    docker:
      - image: python:3.7.4-stretch
    environment:
      PYTHONPATH: /root/savoten
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    working_directory: /root/savoten
    steps:
      - checkout
      - run:
          name: Install pipenv
          command: |
              pip install --upgrade pip
              pip install pipenv
              pipenv install -d --skip-lock
      - run:
          name: Run test
          command: pipenv run scripts/run_tests
