version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Create .env
          command: |
            cat << EOF >> .env
            UID=$(id -u)
            GID=$(id -g)
            EOF
      - run:
          name: Build Docker Image
          command: docker-compose build
      - run:
          name: Docker-compose Up
          command: docker-compose up -d
      - run:
          name: Run tests
          command: docker-compose exec app pipenv run scripts/run_tests